---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reporting-test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: reporting-test
    spec:
      containers:
      - name: reporting-test
        image: nginx:1.7.9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030 # informational

